// Generated by Wrangler by running `wrangler types`
// Runtime types from `@cloudflare/workers-types`

import type { VpsJob } from "./src/queue/types";

interface Env {
  VPS_QUEUE: Queue<VpsJob>;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_BOT_TOKEN: string;
  CONOHA_TENANT_ID: string;
  CONOHA_USERNAME: string;
  CONOHA_PASSWORD: string;
  CONOHA_IDENTITY_ENDPOINT: string;
  CONOHA_COMPUTE_ENDPOINT: string;
  CONOHA_IMAGE_ENDPOINT: string;
}
